unit FeeUtil;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, Grids, Buttons, ExtCtrls;
type
  TFrmFeeUtil=class(TForm)
    Panel1: TPanel;
    FGrid: TStringGrid;
    EdFindID: TEdit;
    Label1: TLabel;
    Label2: TLabel;
    EdFindPC: TEdit;
    OpenDialog1: TOpenDialog;
    Label3: TLabel;
    BtnConvert: TSpeedButton;
    BtnFindId: TSpeedButton;
    BtnFindIdAll: TSpeedButton;
    BtnFindGroup: TSpeedButton;
    BtnFindPCAll: TSpeedButton;
    BtnAddRcd: TSpeedButton;
    BtnDelRcd: TSpeedButton;
    BtnChangeRcd: TSpeedButton;
    BtnBack: TSpeedButton;
    LbPlus: TLabel;
    procedure BtnConvertClick(Sender : TObject);
    procedure BtnFindIDClick(Sender : TObject);
    procedure FormCreate(Sender : TObject);
    procedure FGridDrawCell(Sender : TObject);
    procedure FGridKeyPress(Sender : TObject);
    procedure EdFindIDKeyPress(Sender : TObject);
    procedure EdFindPCKeyPress(Sender : TObject);
    procedure FormKeyDown(Sender : TObject);
    procedure BtnBackClick(Sender : TObject);
    procedure _PROC_0049DA40(Sender : TObject);
    procedure _PROC_0049DB75(Sender : TObject);
    procedure _PROC_0049DEE4(Sender : TObject);
    procedure _PROC_0049DF14(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmFeeUtil: TFrmFeeUtil;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmFeeUtil.BtnConvertClick(Sender : TObject);
begin
(*
0049D748   55                     push    ebp
0049D749   8BEC                   mov     ebp, esp
0049D74B   83C4F0                 add     esp, -$10
0049D74E   33C9                   xor     ecx, ecx
0049D750   894DF0                 mov     [ebp-$10], ecx
0049D753   8955F4                 mov     [ebp-$0C], edx
0049D756   8945FC                 mov     [ebp-$04], eax
0049D759   33C0                   xor     eax, eax
0049D75B   55                     push    ebp

* Possible String Reference to: 'Èd^ˆˇÎãÂ]√ã¿UãÏÅƒXˇˇˇS3€â]ÏâMÙâU¯â
|                                E¸3¿UhÙ◊I'
|
0049D75C   68ABD74900             push    $0049D7AB

***** TRY
|
0049D761   64FF30                 push    dword ptr fs:[eax]
0049D764   648920                 mov     fs:[eax], esp

* Reference to FrmFeeUtil
|
0049D767   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.OpenDialog1 : TOpenDialog
|
0049D76A   8B80E8020000           mov     eax, [eax+$02E8]
0049D770   8945F8                 mov     [ebp-$08], eax
0049D773   8B45F8                 mov     eax, [ebp-$08]
0049D776   8B10                   mov     edx, [eax]

* Reference to method TOpenDialog.Execute()
|
0049D778   FF523C                 call    dword ptr [edx+$3C]
0049D77B   84C0                   test    al, al
0049D77D   7416                   jz      0049D795
0049D77F   8D55F0                 lea     edx, [ebp-$10]
0049D782   8B45F8                 mov     eax, [ebp-$08]

* Reference to: dialogs.TOpenDialog.GetFileName(TOpenDialog):TFileName;
|
0049D785   E84E71FBFF             call    004548D8
0049D78A   8B55F0                 mov     edx, [ebp-$10]

* Reference to FrmFeeUtil
|
0049D78D   8B45FC                 mov     eax, [ebp-$04]

* Reference to: FeeUtil.Proc_0049D6E4
|
0049D790   E84FFFFFFF             call    0049D6E4
0049D795   33C0                   xor     eax, eax
0049D797   5A                     pop     edx
0049D798   59                     pop     ecx
0049D799   59                     pop     ecx
0049D79A   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ãÂ]√ã¿UãÏÅƒXˇˇˇS3€â]ÏâMÙâU¯âE¸3¿UhÙ
|                                ◊I'
|
0049D79D   68B2D74900             push    $0049D7B2
0049D7A2   8D45F0                 lea     eax, [ebp-$10]

* Reference to: system.@LStrClr(String;String);
|
0049D7A5   E85664F6FF             call    00403C00
0049D7AA   C3                     ret


* Reference to: system.@HandleFinally;
|
0049D7AB   E9645EF6FF             jmp     00403614
0049D7B0   EBF0                   jmp     0049D7A2

****** END
|
0049D7B2   8BE5                   mov     esp, ebp
0049D7B4   5D                     pop     ebp
0049D7B5   C3                     ret

*)
end;

procedure TFrmFeeUtil.BtnFindIDClick(Sender : TObject);
begin
(*
0049D800   55                     push    ebp
0049D801   8BEC                   mov     ebp, esp
0049D803   81C460FFFFFF           add     esp, $FFFFFF60
0049D809   33C9                   xor     ecx, ecx
0049D80B   894DF0                 mov     [ebp-$10], ecx
0049D80E   8955F8                 mov     [ebp-$08], edx
0049D811   8945FC                 mov     [ebp-$04], eax
0049D814   33C0                   xor     eax, eax
0049D816   55                     push    ebp

* Possible String Reference to: 'È◊]ˆˇÎãÂ]√êUãÏÅƒTˇˇˇ3…âMÏâU¯âE¸3¿U
|                                h|ÿI'
|
0049D817   6838D84900             push    $0049D838

***** TRY
|
0049D81C   64FF30                 push    dword ptr fs:[eax]
0049D81F   648920                 mov     fs:[eax], esp
0049D822   33C0                   xor     eax, eax
0049D824   5A                     pop     edx
0049D825   59                     pop     ecx
0049D826   59                     pop     ecx
0049D827   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ãÂ]√êUãÏÅƒTˇˇˇ3…âMÏâU¯âE¸3¿Uh|ÿI'
|
0049D82A   683FD84900             push    $0049D83F
0049D82F   8D45F0                 lea     eax, [ebp-$10]

* Reference to: system.@LStrClr(String;String);
|
0049D832   E8C963F6FF             call    00403C00
0049D837   C3                     ret


* Reference to: system.@HandleFinally;
|
0049D838   E9D75DF6FF             jmp     00403614
0049D83D   EBF0                   jmp     0049D82F

****** END
|
0049D83F   8BE5                   mov     esp, ebp
0049D841   5D                     pop     ebp
0049D842   C3                     ret

*)
end;

procedure TFrmFeeUtil.FormCreate(Sender : TObject);
begin
(*
0049D2A8   55                     push    ebp
0049D2A9   8BEC                   mov     ebp, esp
0049D2AB   83C4F8                 add     esp, -$08
0049D2AE   8955F8                 mov     [ebp-$08], edx
0049D2B1   8945FC                 mov     [ebp-$04], eax
0049D2B4   68E4D34900             push    $0049D3E4
0049D2B9   33C9                   xor     ecx, ecx
0049D2BB   33D2                   xor     edx, edx

* Reference to FrmFeeUtil
|
0049D2BD   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D2C0   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049D2C6   E8A99FFFFF             call    00497274

* Possible String Reference to: 'Loginn / IP'
|
0049D2CB   68F0D34900             push    $0049D3F0
0049D2D0   33C9                   xor     ecx, ecx
0049D2D2   BA01000000             mov     edx, $00000001

* Reference to FrmFeeUtil
|
0049D2D7   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D2DA   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049D2E0   E88F9FFFFF             call    00497274

* Possible String Reference to: 'PC ScrName/NickName'
|
0049D2E5   6804D44900             push    $0049D404
0049D2EA   33C9                   xor     ecx, ecx
0049D2EC   BA02000000             mov     edx, $00000002

* Reference to FrmFeeUtil
|
0049D2F1   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D2F4   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049D2FA   E8759FFFFF             call    00497274

* Possible String Reference to: '¥Î«•¿⁄'
|
0049D2FF   6820D44900             push    $0049D420
0049D304   33C9                   xor     ecx, ecx
0049D306   BA03000000             mov     edx, $00000003

* Reference to FrmFeeUtil
|
0049D30B   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D30E   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049D314   E85B9FFFFF             call    00497274

* Possible String Reference to: 'FeeSelec'
|
0049D319   6830D44900             push    $0049D430
0049D31E   33C9                   xor     ecx, ecx
0049D320   BA04000000             mov     edx, $00000004

* Reference to FrmFeeUtil
|
0049D325   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D328   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049D32E   E8419FFFFF             call    00497274

* Possible String Reference to: 'Dupl'
|
0049D333   6844D44900             push    $0049D444
0049D338   33C9                   xor     ecx, ecx
0049D33A   BA05000000             mov     edx, $00000005

* Reference to FrmFeeUtil
|
0049D33F   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D342   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049D348   E8279FFFFF             call    00497274

* Possible String Reference to: 'Regist'
|
0049D34D   6854D44900             push    $0049D454
0049D352   33C9                   xor     ecx, ecx
0049D354   BA06000000             mov     edx, $00000006

* Reference to FrmFeeUtil
|
0049D359   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D35C   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049D362   E80D9FFFFF             call    00497274

* Possible String Reference to: 'Wate'
|
0049D367   6864D44900             push    $0049D464
0049D36C   33C9                   xor     ecx, ecx
0049D36E   BA07000000             mov     edx, $00000007

* Reference to FrmFeeUtil
|
0049D373   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D376   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049D37C   E8F39EFFFF             call    00497274

* Possible String Reference to: 'LangFe'
|
0049D381   6874D44900             push    $0049D474
0049D386   33C9                   xor     ecx, ecx
0049D388   BA08000000             mov     edx, $00000008

* Reference to FrmFeeUtil
|
0049D38D   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D390   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049D396   E8D99EFFFF             call    00497274

* Possible String Reference to: 'Memo'
|
0049D39B   6884D44900             push    $0049D484
0049D3A0   33C9                   xor     ecx, ecx
0049D3A2   BA09000000             mov     edx, $00000009

* Reference to FrmFeeUtil
|
0049D3A7   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D3AA   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049D3B0   E8BF9EFFFF             call    00497274
0049D3B5   B201                   mov     dl, $01

* Reference to class TStringList
|
0049D3B7   A108014100             mov     eax, dword ptr [$00410108]

* Reference to: system.TObject.Create(TObject;Boolean);
|
0049D3BC   E8C35AF6FF             call    00402E84

* Reference to FrmFeeUtil
|
0049D3C1   8B55FC                 mov     edx, [ebp-$04]

* Reference to field TFrmFeeUtil.OFFS_0318
|
0049D3C4   898218030000           mov     [edx+$0318], eax

* Reference to FrmFeeUtil
|
0049D3CA   8B45FC                 mov     eax, [ebp-$04]
0049D3CD   33D2                   xor     edx, edx

* Reference to field TFrmFeeUtil.OFFS_031C
|
0049D3CF   89901C030000           mov     [eax+$031C], edx
0049D3D5   59                     pop     ecx
0049D3D6   59                     pop     ecx
0049D3D7   5D                     pop     ebp
0049D3D8   C3                     ret

*)
end;

procedure TFrmFeeUtil.FGridDrawCell(Sender : TObject);
begin
(*
0049D48C   55                     push    ebp
0049D48D   8BEC                   mov     ebp, esp
0049D48F   83C4CC                 add     esp, -$34
0049D492   53                     push    ebx
0049D493   56                     push    esi
0049D494   57                     push    edi
0049D495   33DB                   xor     ebx, ebx
0049D497   895DCC                 mov     [ebp-$34], ebx
0049D49A   895DD0                 mov     [ebp-$30], ebx
0049D49D   895DD4                 mov     [ebp-$2C], ebx
0049D4A0   895DD8                 mov     [ebp-$28], ebx
0049D4A3   8B750C                 mov     esi, [ebp+$0C]
0049D4A6   8D7DDC                 lea     edi, [ebp-$24]
0049D4A9   51                     push    ecx
0049D4AA   B904000000             mov     ecx, $00000004
0049D4AF   F3                     rep
0049D4B0   A5                     movsd
0049D4B1   59                     pop     ecx
0049D4B2   894DF8                 mov     [ebp-$08], ecx
0049D4B5   8955EC                 mov     [ebp-$14], edx
0049D4B8   8945FC                 mov     [ebp-$04], eax
0049D4BB   33C0                   xor     eax, eax
0049D4BD   55                     push    ebp
0049D4BE   68AED64900             push    $0049D6AE

***** TRY
|
0049D4C3   64FF30                 push    dword ptr fs:[eax]
0049D4C6   648920                 mov     fs:[eax], esp
0049D4C9   837D1000               cmp     dword ptr [ebp+$10], +$00
0049D4CD   0F8EC0010000           jle     0049D693

* Reference to FrmFeeUtil
|
0049D4D3   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D4D6   8B80D4020000           mov     eax, [eax+$02D4]
0049D4DC   8945F4                 mov     [ebp-$0C], eax
0049D4DF   8D45D8                 lea     eax, [ebp-$28]
0049D4E2   50                     push    eax
0049D4E3   8B4D10                 mov     ecx, [ebp+$10]
0049D4E6   33D2                   xor     edx, edx

* Reference to FrmFeeUtil
|
0049D4E8   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D4EB   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.GetCells(TStringGrid;Integer;Integer):AnsiString;
|
0049D4F1   E80E9DFFFF             call    00497204
0049D4F6   837DD800               cmp     dword ptr [ebp-$28], +$00
0049D4FA   0F8585000000           jnz     0049D585
0049D500   A0C0D64900             mov     al, byte ptr [$0049D6C0]
0049D505   3A4508                 cmp     al, byte ptr [ebp+$08]
0049D508   751E                   jnz     0049D528

* Reference to FrmFeeUtil
|
0049D50A   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D50D   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to field TStringGrid.Canvas : TCanvas
|
0049D513   8B80F0010000           mov     eax, [eax+$01F0]

* Reference to field TCanvas.Font : TFont
|
0049D519   8B400C                 mov     eax, [eax+$0C]
0049D51C   BAC0C0C000             mov     edx, $00C0C0C0

* Reference to: graphics.TFont.SetColor(TFont;TColor);
|
0049D521   E87ADDF7FF             call    0041B2A0
0049D526   EB1C                   jmp     0049D544

* Reference to FrmFeeUtil
|
0049D528   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D52B   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to field TStringGrid.Canvas : TCanvas
|
0049D531   8B80F0010000           mov     eax, [eax+$01F0]

* Reference to field TCanvas.Font : TFont
|
0049D537   8B400C                 mov     eax, [eax+$0C]
0049D53A   BA80808000             mov     edx, $00808080

* Reference to: graphics.TFont.SetColor(TFont;TColor);
|
0049D53F   E85CDDF7FF             call    0041B2A0
0049D544   8D45D4                 lea     eax, [ebp-$2C]
0049D547   50                     push    eax
0049D548   8B4D10                 mov     ecx, [ebp+$10]
0049D54B   8B55F8                 mov     edx, [ebp-$08]

* Reference to FrmFeeUtil
|
0049D54E   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D551   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.GetCells(TStringGrid;Integer;Integer):AnsiString;
|
0049D557   E8A89CFFFF             call    00497204
0049D55C   8B45D4                 mov     eax, [ebp-$2C]
0049D55F   50                     push    eax
0049D560   8B4DE0                 mov     ecx, [ebp-$20]
0049D563   83C102                 add     ecx, +$02
0049D566   8B55DC                 mov     edx, [ebp-$24]
0049D569   83C202                 add     edx, +$02

* Reference to FrmFeeUtil
|
0049D56C   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D56F   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to field TStringGrid.Canvas : TCanvas
|
0049D575   8B80F0010000           mov     eax, [eax+$01F0]

* Reference to: graphics.TCanvas.TextOut(TCanvas;Integer;Integer;AnsiString);
|
0049D57B   E8D8EAF7FF             call    0041C058
0049D580   E90E010000             jmp     0049D693
0049D585   837DF804               cmp     dword ptr [ebp-$08], +$04
0049D589   0F8504010000           jnz     0049D693

* Reference to FrmFeeUtil
|
0049D58F   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D592   8B80D4020000           mov     eax, [eax+$02D4]
0049D598   8945F0                 mov     [ebp-$10], eax
0049D59B   8D45D0                 lea     eax, [ebp-$30]
0049D59E   50                     push    eax
0049D59F   8B4D10                 mov     ecx, [ebp+$10]
0049D5A2   8B55F8                 mov     edx, [ebp-$08]

* Reference to FrmFeeUtil
|
0049D5A5   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D5A8   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.GetCells(TStringGrid;Integer;Integer):AnsiString;
|
0049D5AE   E8519CFFFF             call    00497204
0049D5B3   8B45D0                 mov     eax, [ebp-$30]

* Possible String Reference to: 'Quanta'
|
0049D5B6   BACCD64900             mov     edx, $0049D6CC

* Reference to: system.@LStrCmp;
|
0049D5BB   E8D069F6FF             call    00403F90
0049D5C0   7569                   jnz     0049D62B
0049D5C2   A0C0D64900             mov     al, byte ptr [$0049D6C0]
0049D5C7   3A4508                 cmp     al, byte ptr [ebp+$08]
0049D5CA   751E                   jnz     0049D5EA

* Reference to FrmFeeUtil
|
0049D5CC   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D5CF   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to field TStringGrid.Canvas : TCanvas
|
0049D5D5   8B80F0010000           mov     eax, [eax+$01F0]

* Reference to field TCanvas.Font : TFont
|
0049D5DB   8B400C                 mov     eax, [eax+$0C]
0049D5DE   BA00008000             mov     edx, $00800000

* Reference to: graphics.TFont.SetColor(TFont;TColor);
|
0049D5E3   E8B8DCF7FF             call    0041B2A0
0049D5E8   EB1C                   jmp     0049D606

* Reference to FrmFeeUtil
|
0049D5EA   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D5ED   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to field TStringGrid.Canvas : TCanvas
|
0049D5F3   8B80F0010000           mov     eax, [eax+$01F0]

* Reference to field TCanvas.Font : TFont
|
0049D5F9   8B400C                 mov     eax, [eax+$0C]
0049D5FC   BA0000FF00             mov     edx, $00FF0000

* Reference to: graphics.TFont.SetColor(TFont;TColor);
|
0049D601   E89ADCF7FF             call    0041B2A0

* Possible String Reference to: 'Quanta'
|
0049D606   68CCD64900             push    $0049D6CC
0049D60B   8B4DE0                 mov     ecx, [ebp-$20]
0049D60E   83C102                 add     ecx, +$02
0049D611   8B55DC                 mov     edx, [ebp-$24]
0049D614   83C202                 add     edx, +$02

* Reference to FrmFeeUtil
|
0049D617   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D61A   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to field TStringGrid.Canvas : TCanvas
|
0049D620   8B80F0010000           mov     eax, [eax+$01F0]

* Reference to: graphics.TCanvas.TextOut(TCanvas;Integer;Integer;AnsiString);
|
0049D626   E82DEAF7FF             call    0041C058
0049D62B   8D45CC                 lea     eax, [ebp-$34]
0049D62E   50                     push    eax
0049D62F   8B4D10                 mov     ecx, [ebp+$10]
0049D632   8B55F8                 mov     edx, [ebp-$08]

* Reference to FrmFeeUtil
|
0049D635   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D638   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.GetCells(TStringGrid;Integer;Integer):AnsiString;
|
0049D63E   E8C19BFFFF             call    00497204
0049D643   8B45CC                 mov     eax, [ebp-$34]

* Possible String Reference to: 'NoCh'
|
0049D646   BADCD64900             mov     edx, $0049D6DC

* Reference to: system.@LStrCmp;
|
0049D64B   E84069F6FF             call    00403F90
0049D650   7541                   jnz     0049D693

* Reference to FrmFeeUtil
|
0049D652   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D655   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to field TStringGrid.Canvas : TCanvas
|
0049D65B   8B80F0010000           mov     eax, [eax+$01F0]

* Reference to field TCanvas.Font : TFont
|
0049D661   8B400C                 mov     eax, [eax+$0C]
0049D664   BA00800000             mov     edx, $00008000

* Reference to: graphics.TFont.SetColor(TFont;TColor);
|
0049D669   E832DCF7FF             call    0041B2A0

* Possible String Reference to: 'NoCh'
|
0049D66E   68DCD64900             push    $0049D6DC
0049D673   8B4DE0                 mov     ecx, [ebp-$20]
0049D676   83C102                 add     ecx, +$02
0049D679   8B55DC                 mov     edx, [ebp-$24]
0049D67C   83C202                 add     edx, +$02

* Reference to FrmFeeUtil
|
0049D67F   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D682   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to field TStringGrid.Canvas : TCanvas
|
0049D688   8B80F0010000           mov     eax, [eax+$01F0]

* Reference to: graphics.TCanvas.TextOut(TCanvas;Integer;Integer;AnsiString);
|
0049D68E   E8C5E9F7FF             call    0041C058
0049D693   33C0                   xor     eax, eax
0049D695   5A                     pop     edx
0049D696   59                     pop     ecx
0049D697   59                     pop     ecx
0049D698   648910                 mov     fs:[eax], edx

****** FINALLY
|
0049D69B   68B5D64900             push    $0049D6B5
0049D6A0   8D45CC                 lea     eax, [ebp-$34]
0049D6A3   BA04000000             mov     edx, $00000004

* Reference to: system.@LStrArrayClr;
|
0049D6A8   E87765F6FF             call    00403C24
0049D6AD   C3                     ret


* Reference to: system.@HandleFinally;
|
0049D6AE   E9615FF6FF             jmp     00403614
0049D6B3   EBEB                   jmp     0049D6A0

****** END
|
0049D6B5   5F                     pop     edi
0049D6B6   5E                     pop     esi
0049D6B7   5B                     pop     ebx
0049D6B8   8BE5                   mov     esp, ebp
0049D6BA   5D                     pop     ebp
0049D6BB   C20C00                 ret     $000C

*)
end;

procedure TFrmFeeUtil.FGridKeyPress(Sender : TObject);
begin
(*
0049D954   55                     push    ebp
0049D955   8BEC                   mov     ebp, esp
0049D957   83C4F4                 add     esp, -$0C
0049D95A   894DF8                 mov     [ebp-$08], ecx
0049D95D   8955F4                 mov     [ebp-$0C], edx
0049D960   8945FC                 mov     [ebp-$04], eax
0049D963   8B45F8                 mov     eax, [ebp-$08]
0049D966   8A00                   mov     al, byte ptr [eax]
0049D968   2C0D                   sub     al, $0D
0049D96A   740A                   jz      0049D976
0049D96C   2C1E                   sub     al, $1E
0049D96E   7419                   jz      0049D989
0049D970   2C02                   sub     al, $02
0049D972   742E                   jz      0049D9A2
0049D974   EB43                   jmp     0049D9B9
0049D976   8B45F8                 mov     eax, [ebp-$08]
0049D979   C60000                 mov     byte ptr [eax], $00

* Reference to FrmFeeUtil
|
0049D97C   8B55FC                 mov     edx, [ebp-$04]

* Reference to FrmFeeUtil
|
0049D97F   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TFrmFeeUtil.FGridDblClick()
|
0049D982   E889FFFFFF             call    0049D910
0049D987   EB30                   jmp     0049D9B9

* Reference to FrmFeeUtil
|
0049D989   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D98C   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to field TStringGrid.Row : Longint
|
0049D992   8B9014020000           mov     edx, [eax+$0214]

* Reference to FrmFeeUtil
|
0049D998   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TFrmFeeUtil._PROC_0049DA40()
|
0049D99B   E8A0000000             call    0049DA40
0049D9A0   EB17                   jmp     0049D9B9

* Reference to FrmFeeUtil
|
0049D9A2   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D9A5   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to field TStringGrid.Row : Longint
|
0049D9AB   8B9014020000           mov     edx, [eax+$0214]

* Reference to FrmFeeUtil
|
0049D9B1   8B45FC                 mov     eax, [ebp-$04]

* Reference to: FeeUtil.Proc_0049DB74
|
0049D9B4   E8BB010000             call    0049DB74
0049D9B9   8BE5                   mov     esp, ebp
0049D9BB   5D                     pop     ebp
0049D9BC   C3                     ret

*)
end;

procedure TFrmFeeUtil.EdFindIDKeyPress(Sender : TObject);
begin
(*
0049D9C0   55                     push    ebp
0049D9C1   8BEC                   mov     ebp, esp
0049D9C3   83C4F4                 add     esp, -$0C
0049D9C6   894DF8                 mov     [ebp-$08], ecx
0049D9C9   8955F4                 mov     [ebp-$0C], edx
0049D9CC   8945FC                 mov     [ebp-$04], eax
0049D9CF   8B45F8                 mov     eax, [ebp-$08]
0049D9D2   80380D                 cmp     byte ptr [eax], $0D
0049D9D5   7522                   jnz     0049D9F9
0049D9D7   8B45F8                 mov     eax, [ebp-$08]
0049D9DA   C60000                 mov     byte ptr [eax], $00

* Reference to FrmFeeUtil
|
0049D9DD   8B55FC                 mov     edx, [ebp-$04]

* Reference to FrmFeeUtil
|
0049D9E0   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TFrmFeeUtil.BtnFindIDAllClick()
|
0049D9E3   E85CFEFFFF             call    0049D844

* Reference to FrmFeeUtil
|
0049D9E8   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049D9EB   8B80D4020000           mov     eax, [eax+$02D4]
0049D9F1   8B10                   mov     edx, [eax]

* Reference to method TStringGrid.SetFocus()
|
0049D9F3   FF92B0000000           call    dword ptr [edx+$00B0]
0049D9F9   8BE5                   mov     esp, ebp
0049D9FB   5D                     pop     ebp
0049D9FC   C3                     ret

*)
end;

procedure TFrmFeeUtil.EdFindPCKeyPress(Sender : TObject);
begin
(*
0049DA00   55                     push    ebp
0049DA01   8BEC                   mov     ebp, esp
0049DA03   83C4F4                 add     esp, -$0C
0049DA06   894DF8                 mov     [ebp-$08], ecx
0049DA09   8955F4                 mov     [ebp-$0C], edx
0049DA0C   8945FC                 mov     [ebp-$04], eax
0049DA0F   8B45F8                 mov     eax, [ebp-$08]
0049DA12   80380D                 cmp     byte ptr [eax], $0D
0049DA15   7522                   jnz     0049DA39
0049DA17   8B45F8                 mov     eax, [ebp-$08]
0049DA1A   C60000                 mov     byte ptr [eax], $00

* Reference to FrmFeeUtil
|
0049DA1D   8B55FC                 mov     edx, [ebp-$04]

* Reference to FrmFeeUtil
|
0049DA20   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TFrmFeeUtil.BtnFindPCAllClick()
|
0049DA23   E8A4FEFFFF             call    0049D8CC

* Reference to FrmFeeUtil
|
0049DA28   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049DA2B   8B80D4020000           mov     eax, [eax+$02D4]
0049DA31   8B10                   mov     edx, [eax]

* Reference to method TStringGrid.SetFocus()
|
0049DA33   FF92B0000000           call    dword ptr [edx+$00B0]
0049DA39   8BE5                   mov     esp, ebp
0049DA3B   5D                     pop     ebp
0049DA3C   C3                     ret

*)
end;

procedure TFrmFeeUtil.FormKeyDown(Sender : TObject);
begin
(*
0049DDA4   55                     push    ebp
0049DDA5   8BEC                   mov     ebp, esp
0049DDA7   83C4F4                 add     esp, -$0C
0049DDAA   894DF8                 mov     [ebp-$08], ecx
0049DDAD   8955F4                 mov     [ebp-$0C], edx
0049DDB0   8945FC                 mov     [ebp-$04], eax
0049DDB3   8B45F8                 mov     eax, [ebp-$08]
0049DDB6   0FB700                 movzx   eax, word ptr [eax]
0049DDB9   83F873                 cmp     eax, +$73
0049DDBC   7F11                   jnle    0049DDCF
0049DDBE   7431                   jz      0049DDF1
0049DDC0   83E80D                 sub     eax, +$0D
0049DDC3   7459                   jz      0049DE1E
0049DDC5   83E820                 sub     eax, +$20
0049DDC8   7434                   jz      0049DDFE
0049DDCA   48                     dec     eax
0049DDCB   743E                   jz      0049DE0B
0049DDCD   EB60                   jmp     0049DE2F
0049DDCF   83E874                 sub     eax, +$74
0049DDD2   7410                   jz      0049DDE4
0049DDD4   48                     dec     eax
0049DDD5   7558                   jnz     0049DE2F

* Reference to FrmFeeUtil
|
0049DDD7   8B55FC                 mov     edx, [ebp-$04]

* Reference to FrmFeeUtil
|
0049DDDA   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TFrmFeeUtil.BtnFindIDAllClick()
|
0049DDDD   E862FAFFFF             call    0049D844
0049DDE2   EB4B                   jmp     0049DE2F

* Reference to FrmFeeUtil
|
0049DDE4   8B55FC                 mov     edx, [ebp-$04]

* Reference to FrmFeeUtil
|
0049DDE7   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TFrmFeeUtil.BtnFindPCAllClick()
|
0049DDEA   E8DDFAFFFF             call    0049D8CC
0049DDEF   EB3E                   jmp     0049DE2F

* Reference to FrmFeeUtil
|
0049DDF1   8B55FC                 mov     edx, [ebp-$04]

* Reference to FrmFeeUtil
|
0049DDF4   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TFrmFeeUtil.BtnBackClick()
|
0049DDF7   E83C000000             call    0049DE38
0049DDFC   EB31                   jmp     0049DE2F

* Reference to FrmFeeUtil
|
0049DDFE   8B55FC                 mov     edx, [ebp-$04]

* Reference to FrmFeeUtil
|
0049DE01   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TFrmFeeUtil.BtnAddRcdClick()
|
0049DE04   E8F3FEFFFF             call    0049DCFC
0049DE09   EB24                   jmp     0049DE2F
0049DE0B   F6450804               test    byte ptr [ebp+$08], $04
0049DE0F   741E                   jz      0049DE2F

* Reference to FrmFeeUtil
|
0049DE11   8B55FC                 mov     edx, [ebp-$04]

* Reference to FrmFeeUtil
|
0049DE14   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TFrmFeeUtil.BtnDelRcdClick()
|
0049DE17   E8F4FEFFFF             call    0049DD10
0049DE1C   EB11                   jmp     0049DE2F
0049DE1E   F6450804               test    byte ptr [ebp+$08], $04
0049DE22   740B                   jz      0049DE2F

* Reference to FrmFeeUtil
|
0049DE24   8B55FC                 mov     edx, [ebp-$04]

* Reference to FrmFeeUtil
|
0049DE27   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TFrmFeeUtil.BtnChangeRcdClick()
|
0049DE2A   E821FFFFFF             call    0049DD50
0049DE2F   8BE5                   mov     esp, ebp
0049DE31   5D                     pop     ebp
0049DE32   C20400                 ret     $0004

*)
end;

procedure TFrmFeeUtil.BtnBackClick(Sender : TObject);
begin
(*
0049DE38   55                     push    ebp
0049DE39   8BEC                   mov     ebp, esp
0049DE3B   83C4F4                 add     esp, -$0C
0049DE3E   53                     push    ebx
0049DE3F   33C9                   xor     ecx, ecx
0049DE41   894DF4                 mov     [ebp-$0C], ecx
0049DE44   8955F8                 mov     [ebp-$08], edx
0049DE47   8945FC                 mov     [ebp-$04], eax
0049DE4A   33C0                   xor     eax, eax
0049DE4C   55                     push    ebp

* Possible String Reference to: 'È:WˆˇÎ[ãÂ]√ç@'
|
0049DE4D   68D5DE4900             push    $0049DED5

***** TRY
|
0049DE52   64FF30                 push    dword ptr fs:[eax]
0049DE55   648920                 mov     fs:[eax], esp

* Reference to FrmFeeUtil
|
0049DE58   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TFrmFeeUtil.OFFS_0318
|
0049DE5B   8B8018030000           mov     eax, [eax+$0318]
0049DE61   8B10                   mov     edx, [eax]
0049DE63   FF5214                 call    dword ptr [edx+$14]
0049DE66   48                     dec     eax
0049DE67   7E51                   jle     0049DEBA
0049DE69   33D2                   xor     edx, edx

* Reference to FrmFeeUtil
|
0049DE6B   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TFrmFeeUtil.OFFS_0318
|
0049DE6E   8B8018030000           mov     eax, [eax+$0318]
0049DE74   8B08                   mov     ecx, [eax]
0049DE76   FF5144                 call    dword ptr [ecx+$44]
0049DE79   8D4DF4                 lea     ecx, [ebp-$0C]
0049DE7C   33D2                   xor     edx, edx

* Reference to FrmFeeUtil
|
0049DE7E   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TFrmFeeUtil.OFFS_0318
|
0049DE81   8B8018030000           mov     eax, [eax+$0318]
0049DE87   8B18                   mov     ebx, [eax]
0049DE89   FF530C                 call    dword ptr [ebx+$0C]
0049DE8C   8B55F4                 mov     edx, [ebp-$0C]

* Reference to FrmFeeUtil
|
0049DE8F   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.EdFindPC : TEdit
|
0049DE92   8B80E4020000           mov     eax, [eax+$02E4]

* Reference to: controls.TControl.SetText(TControl;TCaption);
|
0049DE98   E8F33EF9FF             call    00431D90

* Reference to FrmFeeUtil
|
0049DE9D   8B55FC                 mov     edx, [ebp-$04]

* Reference to FrmFeeUtil
|
0049DEA0   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TFrmFeeUtil.BtnFindPCAllClick()
|
0049DEA3   E824FAFFFF             call    0049D8CC
0049DEA8   33D2                   xor     edx, edx

* Reference to FrmFeeUtil
|
0049DEAA   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TFrmFeeUtil.OFFS_0318
|
0049DEAD   8B8018030000           mov     eax, [eax+$0318]
0049DEB3   8B08                   mov     ecx, [eax]
0049DEB5   FF5144                 call    dword ptr [ecx+$44]
0049DEB8   EB05                   jmp     0049DEBF

* Reference to: Unit_00407FB4.Proc_0040CBEC
|
0049DEBA   E82DEDF6FF             call    0040CBEC
0049DEBF   33C0                   xor     eax, eax
0049DEC1   5A                     pop     edx
0049DEC2   59                     pop     ecx
0049DEC3   59                     pop     ecx
0049DEC4   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[ãÂ]√ç@'
|
0049DEC7   68DCDE4900             push    $0049DEDC
0049DECC   8D45F4                 lea     eax, [ebp-$0C]

* Reference to: system.@LStrClr(String;String);
|
0049DECF   E82C5DF6FF             call    00403C00
0049DED4   C3                     ret


* Reference to: system.@HandleFinally;
|
0049DED5   E93A57F6FF             jmp     00403614
0049DEDA   EBF0                   jmp     0049DECC

****** END
|
0049DEDC   5B                     pop     ebx
0049DEDD   8BE5                   mov     esp, ebp
0049DEDF   5D                     pop     ebp
0049DEE0   C3                     ret

*)
end;

procedure TFrmFeeUtil._PROC_0049DA40(Sender : TObject);
begin
(*
0049DA40   55                     push    ebp
0049DA41   8BEC                   mov     ebp, esp
0049DA43   33C9                   xor     ecx, ecx
0049DA45   51                     push    ecx
0049DA46   51                     push    ecx
0049DA47   51                     push    ecx
0049DA48   51                     push    ecx
0049DA49   51                     push    ecx
0049DA4A   51                     push    ecx
0049DA4B   51                     push    ecx
0049DA4C   8955F8                 mov     [ebp-$08], edx
0049DA4F   8945FC                 mov     [ebp-$04], eax
0049DA52   33C0                   xor     eax, eax
0049DA54   55                     push    ebp

* Possible String Reference to: 'È≈ZˆˇÎÎãÂ]√'
|
0049DA55   684ADB4900             push    $0049DB4A

***** TRY
|
0049DA5A   64FF30                 push    dword ptr fs:[eax]
0049DA5D   648920                 mov     fs:[eax], esp

* Reference to FrmFeeUtil
|
0049DA60   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TFrmFeeUtil.OFFS_031C
|
0049DA63   83B81C03000000         cmp     dword ptr [eax+$031C], +$00
0049DA6A   7F0A                   jnle    0049DA76

* Reference to: Unit_00407FB4.Proc_0040CBEC
|
0049DA6C   E87BF1F6FF             call    0040CBEC
0049DA71   E9B9000000             jmp     0049DB2F
0049DA76   8D45F0                 lea     eax, [ebp-$10]
0049DA79   50                     push    eax
0049DA7A   8B4DF8                 mov     ecx, [ebp-$08]
0049DA7D   BA04000000             mov     edx, $00000004

* Reference to FrmFeeUtil
|
0049DA82   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049DA85   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.GetCells(TStringGrid;Integer;Integer):AnsiString;
|
0049DA8B   E87497FFFF             call    00497204
0049DA90   8B45F0                 mov     eax, [ebp-$10]

* Possible String Reference to: 'Quanta'
|
0049DA93   BA60DB4900             mov     edx, $0049DB60

* Reference to: system.@LStrCmp;
|
0049DA98   E8F364F6FF             call    00403F90
0049DA9D   7469                   jz      0049DB08
0049DA9F   8D45EC                 lea     eax, [ebp-$14]
0049DAA2   50                     push    eax
0049DAA3   8B4DF8                 mov     ecx, [ebp-$08]
0049DAA6   33D2                   xor     edx, edx

* Reference to FrmFeeUtil
|
0049DAA8   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049DAAB   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.GetCells(TStringGrid;Integer;Integer):AnsiString;
|
0049DAB1   E84E97FFFF             call    00497204
0049DAB6   8B45EC                 mov     eax, [ebp-$14]
0049DAB9   BA70DB4900             mov     edx, $0049DB70

* Reference to: system.@LStrCmp;
|
0049DABE   E8CD64F6FF             call    00403F90
0049DAC3   7543                   jnz     0049DB08
0049DAC5   8D45E8                 lea     eax, [ebp-$18]
0049DAC8   50                     push    eax
0049DAC9   8B4DF8                 mov     ecx, [ebp-$08]
0049DACC   BA07000000             mov     edx, $00000007

* Reference to FrmFeeUtil
|
0049DAD1   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049DAD4   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.GetCells(TStringGrid;Integer;Integer):AnsiString;
|
0049DADA   E82597FFFF             call    00497204
0049DADF   8B45E8                 mov     eax, [ebp-$18]
0049DAE2   33D2                   xor     edx, edx

* Reference to: Unit_004590EC.Proc_004592B4
|
0049DAE4   E8CBB7FBFF             call    004592B4
0049DAE9   8945F4                 mov     [ebp-$0C], eax
0049DAEC   FF45F4                 inc     dword ptr [ebp-$0C]

* Reference to FrmFeeUtil
|
0049DAEF   8B45FC                 mov     eax, [ebp-$04]
0049DAF2   FF881C030000           dec     dword ptr [eax+$031C]
0049DAF8   8B4DF4                 mov     ecx, [ebp-$0C]
0049DAFB   8B55F8                 mov     edx, [ebp-$08]

* Reference to FrmFeeUtil
|
0049DAFE   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TFrmFeeUtil._PROC_0049D7B8()
|
0049DB01   E8B2FCFFFF             call    0049D7B8
0049DB06   EB05                   jmp     0049DB0D

* Reference to: Unit_00407FB4.Proc_0040CBEC
|
0049DB08   E8DFF0F6FF             call    0040CBEC
0049DB0D   8D55E4                 lea     edx, [ebp-$1C]

* Reference to FrmFeeUtil
|
0049DB10   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TFrmFeeUtil.OFFS_031C
|
0049DB13   8B801C030000           mov     eax, [eax+$031C]

* Reference to: Unit_00407FB4.Proc_004090F0
|
0049DB19   E8D2B5F6FF             call    004090F0
0049DB1E   8B55E4                 mov     edx, [ebp-$1C]

* Reference to FrmFeeUtil
|
0049DB21   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.LbPlus : TLabel
|
0049DB24   8B8014030000           mov     eax, [eax+$0314]

* Reference to: controls.TControl.SetText(TControl;TCaption);
|
0049DB2A   E86142F9FF             call    00431D90
0049DB2F   33C0                   xor     eax, eax
0049DB31   5A                     pop     edx
0049DB32   59                     pop     ecx
0049DB33   59                     pop     ecx
0049DB34   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ãÂ]√'
|
0049DB37   6851DB4900             push    $0049DB51
0049DB3C   8D45E4                 lea     eax, [ebp-$1C]
0049DB3F   BA04000000             mov     edx, $00000004

* Reference to: system.@LStrArrayClr;
|
0049DB44   E8DB60F6FF             call    00403C24
0049DB49   C3                     ret


* Reference to: system.@HandleFinally;
|
0049DB4A   E9C55AF6FF             jmp     00403614
0049DB4F   EBEB                   jmp     0049DB3C

****** END
|
0049DB51   8BE5                   mov     esp, ebp
0049DB53   5D                     pop     ebp
0049DB54   C3                     ret

*)
end;

procedure TFrmFeeUtil._PROC_0049DB75(Sender : TObject);
begin
(*
0049DB75   8BEC                   mov     ebp, esp
0049DB77   83C4D8                 add     esp, -$28
0049DB7A   33C9                   xor     ecx, ecx
0049DB7C   894DD8                 mov     [ebp-$28], ecx
0049DB7F   894DE4                 mov     [ebp-$1C], ecx
0049DB82   894DE8                 mov     [ebp-$18], ecx
0049DB85   894DEC                 mov     [ebp-$14], ecx
0049DB88   894DF0                 mov     [ebp-$10], ecx
0049DB8B   8955F8                 mov     [ebp-$08], edx
0049DB8E   8945FC                 mov     [ebp-$04], eax
0049DB91   33C0                   xor     eax, eax
0049DB93   55                     push    ebp

* Possible String Reference to: 'È=YˆˇÎ„ãÂ]√'
|
0049DB94   68D2DC4900             push    $0049DCD2

***** TRY
|
0049DB99   64FF30                 push    dword ptr fs:[eax]
0049DB9C   648920                 mov     fs:[eax], esp
0049DB9F   8D45F0                 lea     eax, [ebp-$10]
0049DBA2   50                     push    eax
0049DBA3   8B4DF8                 mov     ecx, [ebp-$08]
0049DBA6   BA04000000             mov     edx, $00000004

* Reference to FrmFeeUtil
|
0049DBAB   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049DBAE   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.GetCells(TStringGrid;Integer;Integer):AnsiString;
|
0049DBB4   E84B96FFFF             call    00497204
0049DBB9   8B45F0                 mov     eax, [ebp-$10]

* Possible String Reference to: 'Quanta'
|
0049DBBC   BAE8DC4900             mov     edx, $0049DCE8

* Reference to: system.@LStrCmp;
|
0049DBC1   E8CA63F6FF             call    00403F90
0049DBC6   0F84BC000000           jz      0049DC88
0049DBCC   8D45EC                 lea     eax, [ebp-$14]
0049DBCF   50                     push    eax
0049DBD0   8B4DF8                 mov     ecx, [ebp-$08]
0049DBD3   33D2                   xor     edx, edx

* Reference to FrmFeeUtil
|
0049DBD5   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049DBD8   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.GetCells(TStringGrid;Integer;Integer):AnsiString;
|
0049DBDE   E82196FFFF             call    00497204
0049DBE3   8B45EC                 mov     eax, [ebp-$14]
0049DBE6   BAF8DC4900             mov     edx, $0049DCF8

* Reference to: system.@LStrCmp;
|
0049DBEB   E8A063F6FF             call    00403F90
0049DBF0   0F8592000000           jnz     0049DC88
0049DBF6   8D45E8                 lea     eax, [ebp-$18]
0049DBF9   50                     push    eax
0049DBFA   8B4DF8                 mov     ecx, [ebp-$08]
0049DBFD   BA07000000             mov     edx, $00000007

* Reference to FrmFeeUtil
|
0049DC02   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049DC05   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.GetCells(TStringGrid;Integer;Integer):AnsiString;
|
0049DC0B   E8F495FFFF             call    00497204
0049DC10   8B45E8                 mov     eax, [ebp-$18]
0049DC13   33D2                   xor     edx, edx

* Reference to: Unit_004590EC.Proc_004592B4
|
0049DC15   E89AB6FBFF             call    004592B4
0049DC1A   8945F4                 mov     [ebp-$0C], eax
0049DC1D   837DF400               cmp     dword ptr [ebp-$0C], +$00
0049DC21   7E6A                   jle     0049DC8D
0049DC23   FF4DF4                 dec     dword ptr [ebp-$0C]
0049DC26   8D45E4                 lea     eax, [ebp-$1C]
0049DC29   50                     push    eax
0049DC2A   8B4DF8                 mov     ecx, [ebp-$08]
0049DC2D   BA06000000             mov     edx, $00000006

* Reference to FrmFeeUtil
|
0049DC32   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.FGrid : TStringGrid
|
0049DC35   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TStringGrid.GetCells(TStringGrid;Integer;Integer):AnsiString;
|
0049DC3B   E8C495FFFF             call    00497204
0049DC40   8B45E4                 mov     eax, [ebp-$1C]

* Reference to: Unit_00407FB4.Proc_0040B9B4
|
0049DC43   E86CDDF6FF             call    0040B9B4
0049DC48   83C4F8                 add     esp, -$08
0049DC4B   DD1C24                 fstp    qword ptr [esp]
0049DC4E   9B                     wait
0049DC4F   8B45F4                 mov     eax, [ebp-$0C]

* Reference to : TQuickIdList._PROC_0045C0DC()
|
0049DC52   E885E4FBFF             call    0045C0DC
0049DC57   DD5DDC                 fstp    qword ptr [ebp-$24]
0049DC5A   9B                     wait

* Reference to: Unit_00407FB4.Proc_0040A530
|
0049DC5B   E8D0C8F6FF             call    0040A530
0049DC60   DC5DDC                 fcomp   qword ptr [ebp-$24]
0049DC63   DFE0                   fstsw   ax
0049DC65   9E                     sahf
0049DC66   7719                   jnbe    0049DC81

* Reference to FrmFeeUtil
|
0049DC68   8B45FC                 mov     eax, [ebp-$04]
0049DC6B   FF801C030000           inc     dword ptr [eax+$031C]
0049DC71   8B4DF4                 mov     ecx, [ebp-$0C]
0049DC74   8B55F8                 mov     edx, [ebp-$08]

* Reference to FrmFeeUtil
|
0049DC77   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TFrmFeeUtil._PROC_0049D7B8()
|
0049DC7A   E839FBFFFF             call    0049D7B8
0049DC7F   EB0C                   jmp     0049DC8D

* Reference to: Unit_00407FB4.Proc_0040CBEC
|
0049DC81   E866EFF6FF             call    0040CBEC
0049DC86   EB05                   jmp     0049DC8D

* Reference to: Unit_00407FB4.Proc_0040CBEC
|
0049DC88   E85FEFF6FF             call    0040CBEC
0049DC8D   8D55D8                 lea     edx, [ebp-$28]

* Reference to FrmFeeUtil
|
0049DC90   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TFrmFeeUtil.OFFS_031C
|
0049DC93   8B801C030000           mov     eax, [eax+$031C]

* Reference to: Unit_00407FB4.Proc_004090F0
|
0049DC99   E852B4F6FF             call    004090F0
0049DC9E   8B55D8                 mov     edx, [ebp-$28]

* Reference to FrmFeeUtil
|
0049DCA1   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFeeUtil.LbPlus : TLabel
|
0049DCA4   8B8014030000           mov     eax, [eax+$0314]

* Reference to: controls.TControl.SetText(TControl;TCaption);
|
0049DCAA   E8E140F9FF             call    00431D90
0049DCAF   33C0                   xor     eax, eax
0049DCB1   5A                     pop     edx
0049DCB2   59                     pop     ecx
0049DCB3   59                     pop     ecx
0049DCB4   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ãÂ]√'
|
0049DCB7   68D9DC4900             push    $0049DCD9
0049DCBC   8D45D8                 lea     eax, [ebp-$28]

* Reference to: system.@LStrClr(String;String);
|
0049DCBF   E83C5FF6FF             call    00403C00
0049DCC4   8D45E4                 lea     eax, [ebp-$1C]
0049DCC7   BA04000000             mov     edx, $00000004

* Reference to: system.@LStrArrayClr;
|
0049DCCC   E8535FF6FF             call    00403C24
0049DCD1   C3                     ret


* Reference to: system.@HandleFinally;
|
0049DCD2   E93D59F6FF             jmp     00403614
0049DCD7   EBE3                   jmp     0049DCBC

****** END
|
0049DCD9   8BE5                   mov     esp, ebp
0049DCDB   5D                     pop     ebp
0049DCDC   C3                     ret

*)
end;

procedure TFrmFeeUtil._PROC_0049DEE4(Sender : TObject);
begin
(*
0049DEE4   55                     push    ebp
0049DEE5   8BEC                   mov     ebp, esp
0049DEE7   33C0                   xor     eax, eax
0049DEE9   55                     push    ebp
0049DEEA   6809DF4900             push    $0049DF09

***** TRY
|
0049DEEF   64FF30                 push    dword ptr fs:[eax]
0049DEF2   648920                 mov     fs:[eax], esp
0049DEF5   FF0594DB4A00           inc     dword ptr [$004ADB94]
0049DEFB   33C0                   xor     eax, eax
0049DEFD   5A                     pop     edx
0049DEFE   59                     pop     ecx
0049DEFF   59                     pop     ecx
0049DF00   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√ã¿É-î€J'
|
0049DF03   6810DF4900             push    $0049DF10
0049DF08   C3                     ret


* Reference to: system.@HandleFinally;
|
0049DF09   E90657F6FF             jmp     00403614
0049DF0E   EBF8                   jmp     0049DF08

****** END
|
0049DF10   5D                     pop     ebp
0049DF11   C3                     ret

*)
end;

procedure TFrmFeeUtil._PROC_0049DF14(Sender : TObject);
begin
(*
0049DF14   832D94DB4A0001         sub     dword ptr [$004ADB94], +$01
0049DF1B   C3                     ret

*)
end;

end.
