unit viewrcd;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls,TabNotBk,Grids,ExtCtrls,Buttons,
  ComCtrls, HumDB,Grobal2;
type
  TFrmFDBViewer=class(TForm)
    TabbedNotebook1: TTabbedNotebook;
    HumanGrid: TStringGrid;
    BagItemGrid: TStringGrid;
    UseMagicGrid: TStringGrid;
    SaveItemGrid: TStringGrid;
    procedure FormCreate(Sender : TObject);
    procedure BtnReadOnlyClick(Sender : TObject);
    procedure BtnApplyClick(Sender : TObject);
    procedure ResetPositionClick(Sender : TObject);




    procedure _PROC_0049B9E4(Sender : TObject);
    procedure _PROC_0049BB54(Sender : TObject);
    procedure _PROC_0049BB84(Sender : TObject);
  private
    procedure sub_49A0C0();
    procedure sub_49A9DC();
    procedure sub_49AA84();
    procedure sub_49AB10();
    procedure ShowBagItem(nIndex:Integer;sName:String;Item:TUserItem);

    procedure ShowBagItems();
    procedure ShowUseMagic();
    procedure ShowSaveItem();
    procedure ShowHumanInfo();
    { Private declarations }
  public
    n2F8:Integer;
    s2FC:String;
    ChrRecord:THumDataInfo;
    procedure ShowHumData();
    { Public declarations }
  end ;

var
  FrmFDBViewer: TFrmFDBViewer;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation



{$R *.DFM}

procedure TFrmFDBViewer.FormCreate(Sender : TObject);
//0x0049A024
begin
  sub_49A0C0();
  sub_49A9DC();
  sub_49AA84();
  sub_49AB10();
end;

procedure TFrmFDBViewer.BtnReadOnlyClick(Sender : TObject);
begin
(*
0049B7C8   55                     push    ebp
0049B7C9   8BEC                   mov     ebp, esp
0049B7CB   83C4F8                 add     esp, -$08
0049B7CE   8955F8                 mov     [ebp-$08], edx
0049B7D1   8945FC                 mov     [ebp-$04], eax

* Reference to FrmFDBViewer
|
0049B7D4   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.BtnReadOnly : TSpeedButton
|
0049B7D7   8B80EC020000           mov     eax, [eax+$02EC]

* Reference to field TSpeedButton.Down : Boolean
|
0049B7DD   80B83001000000         cmp     byte ptr [eax+$0130], $00
0049B7E4   0F840E010000           jz      0049B8F8

* Reference to TPasswordDlg instance
|
0049B7EA   A1B4C24A00             mov     eax, dword ptr [$004AC2B4]
0049B7EF   8B00                   mov     eax, [eax]

* Reference to: passwd.Proc_00499CB8
|
0049B7F1   E8C2E4FFFF             call    00499CB8
0049B7F6   84C0                   test    al, al
0049B7F8   0F84E5000000           jz      0049B8E3

* Reference to FrmFDBViewer
|
0049B7FE   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.HumanGrid : TStringGrid
|
0049B801   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to field TStringGrid.Options : TGridOptions
|
0049B807   668B9030020000         mov     dx, word ptr [eax+$0230]
0049B80E   660B15E4B94900         or      dx, word ptr [$0049B9E4]

* Reference to FrmFDBViewer
|
0049B815   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.HumanGrid : TStringGrid
|
0049B818   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TCustomGrid.SetOptions(TCustomGrid;TGridOptions);
|
0049B81E   E84598FFFF             call    00495068

* Reference to FrmFDBViewer
|
0049B823   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.BagItemGrid : TStringGrid
|
0049B826   8B80D8020000           mov     eax, [eax+$02D8]

* Reference to field TStringGrid.Options : TGridOptions
|
0049B82C   668B9030020000         mov     dx, word ptr [eax+$0230]
0049B833   660B15E4B94900         or      dx, word ptr [$0049B9E4]

* Reference to FrmFDBViewer
|
0049B83A   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.BagItemGrid : TStringGrid
|
0049B83D   8B80D8020000           mov     eax, [eax+$02D8]

* Reference to: grids.TCustomGrid.SetOptions(TCustomGrid;TGridOptions);
|
0049B843   E82098FFFF             call    00495068

* Reference to FrmFDBViewer
|
0049B848   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.UseMagicGrid : TStringGrid
|
0049B84B   8B80DC020000           mov     eax, [eax+$02DC]

* Reference to field TStringGrid.Options : TGridOptions
|
0049B851   668B9030020000         mov     dx, word ptr [eax+$0230]
0049B858   660B15E4B94900         or      dx, word ptr [$0049B9E4]

* Reference to FrmFDBViewer
|
0049B85F   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.UseMagicGrid : TStringGrid
|
0049B862   8B80DC020000           mov     eax, [eax+$02DC]

* Reference to: grids.TCustomGrid.SetOptions(TCustomGrid;TGridOptions);
|
0049B868   E8FB97FFFF             call    00495068

* Reference to FrmFDBViewer
|
0049B86D   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.SaveItemGrid : TStringGrid
|
0049B870   8B80E0020000           mov     eax, [eax+$02E0]

* Reference to field TStringGrid.Options : TGridOptions
|
0049B876   668B9030020000         mov     dx, word ptr [eax+$0230]
0049B87D   660B15E4B94900         or      dx, word ptr [$0049B9E4]

* Reference to FrmFDBViewer
|
0049B884   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.SaveItemGrid : TStringGrid
|
0049B887   8B80E0020000           mov     eax, [eax+$02E0]

* Reference to: grids.TCustomGrid.SetOptions(TCustomGrid;TGridOptions);
|
0049B88D   E8D697FFFF             call    00495068
0049B892   BA80800000             mov     edx, $00008080

* Reference to FrmFDBViewer
|
0049B897   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.HumanGrid : TStringGrid
|
0049B89A   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: controls.TControl.SetColor(TControl;TColor);
|
0049B8A0   E84766F9FF             call    00431EEC
0049B8A5   BA80800000             mov     edx, $00008080

* Reference to FrmFDBViewer
|
0049B8AA   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.BagItemGrid : TStringGrid
|
0049B8AD   8B80D8020000           mov     eax, [eax+$02D8]

* Reference to: controls.TControl.SetColor(TControl;TColor);
|
0049B8B3   E83466F9FF             call    00431EEC
0049B8B8   BA80800000             mov     edx, $00008080

* Reference to FrmFDBViewer
|
0049B8BD   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.UseMagicGrid : TStringGrid
|
0049B8C0   8B80DC020000           mov     eax, [eax+$02DC]

* Reference to: controls.TControl.SetColor(TControl;TColor);
|
0049B8C6   E82166F9FF             call    00431EEC
0049B8CB   BA80800000             mov     edx, $00008080

* Reference to FrmFDBViewer
|
0049B8D0   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.SaveItemGrid : TStringGrid
|
0049B8D3   8B80E0020000           mov     eax, [eax+$02E0]

* Reference to: controls.TControl.SetColor(TControl;TColor);
|
0049B8D9   E80E66F9FF             call    00431EEC
0049B8DE   E9FD000000             jmp     0049B9E0
0049B8E3   33D2                   xor     edx, edx

* Reference to FrmFDBViewer
|
0049B8E5   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.BtnReadOnly : TSpeedButton
|
0049B8E8   8B80EC020000           mov     eax, [eax+$02EC]

* Reference to: buttons.TSpeedButton.SetDown(TSpeedButton;Boolean);
|
0049B8EE   E8A9D9FEFF             call    0048929C
0049B8F3   E9E8000000             jmp     0049B9E0

* Reference to FrmFDBViewer
|
0049B8F8   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.HumanGrid : TStringGrid
|
0049B8FB   8B80D4020000           mov     eax, [eax+$02D4]
0049B901   668B15E4B94900         mov     dx, word ptr [$0049B9E4]
0049B908   F7D2                   not     edx 
0049B90A   66239030020000         and     dx, word ptr [eax+$0230]

* Reference to FrmFDBViewer
|
0049B911   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.HumanGrid : TStringGrid
|
0049B914   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: grids.TCustomGrid.SetOptions(TCustomGrid;TGridOptions);
|
0049B91A   E84997FFFF             call    00495068

* Reference to FrmFDBViewer
|
0049B91F   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.BagItemGrid : TStringGrid
|
0049B922   8B80D8020000           mov     eax, [eax+$02D8]
0049B928   668B15E4B94900         mov     dx, word ptr [$0049B9E4]
0049B92F   F7D2                   not     edx 
0049B931   66239030020000         and     dx, word ptr [eax+$0230]

* Reference to FrmFDBViewer
|
0049B938   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.BagItemGrid : TStringGrid
|
0049B93B   8B80D8020000           mov     eax, [eax+$02D8]

* Reference to: grids.TCustomGrid.SetOptions(TCustomGrid;TGridOptions);
|
0049B941   E82297FFFF             call    00495068

* Reference to FrmFDBViewer
|
0049B946   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.UseMagicGrid : TStringGrid
|
0049B949   8B80DC020000           mov     eax, [eax+$02DC]
0049B94F   668B15E4B94900         mov     dx, word ptr [$0049B9E4]
0049B956   F7D2                   not     edx 
0049B958   66239030020000         and     dx, word ptr [eax+$0230]

* Reference to FrmFDBViewer
|
0049B95F   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.UseMagicGrid : TStringGrid
|
0049B962   8B80DC020000           mov     eax, [eax+$02DC]

* Reference to: grids.TCustomGrid.SetOptions(TCustomGrid;TGridOptions);
|
0049B968   E8FB96FFFF             call    00495068

* Reference to FrmFDBViewer
|
0049B96D   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.SaveItemGrid : TStringGrid
|
0049B970   8B80E0020000           mov     eax, [eax+$02E0]
0049B976   668B15E4B94900         mov     dx, word ptr [$0049B9E4]
0049B97D   F7D2                   not     edx 
0049B97F   66239030020000         and     dx, word ptr [eax+$0230]

* Reference to FrmFDBViewer
|
0049B986   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.SaveItemGrid : TStringGrid
|
0049B989   8B80E0020000           mov     eax, [eax+$02E0]

* Reference to: grids.TCustomGrid.SetOptions(TCustomGrid;TGridOptions);
|
0049B98F   E8D496FFFF             call    00495068
0049B994   BA05000080             mov     edx, $80000005

* Reference to FrmFDBViewer
|
0049B999   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.HumanGrid : TStringGrid
|
0049B99C   8B80D4020000           mov     eax, [eax+$02D4]

* Reference to: controls.TControl.SetColor(TControl;TColor);
|
0049B9A2   E84565F9FF             call    00431EEC
0049B9A7   BA05000080             mov     edx, $80000005

* Reference to FrmFDBViewer
|
0049B9AC   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.BagItemGrid : TStringGrid
|
0049B9AF   8B80D8020000           mov     eax, [eax+$02D8]

* Reference to: controls.TControl.SetColor(TControl;TColor);
|
0049B9B5   E83265F9FF             call    00431EEC
0049B9BA   BA05000080             mov     edx, $80000005

* Reference to FrmFDBViewer
|
0049B9BF   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.UseMagicGrid : TStringGrid
|
0049B9C2   8B80DC020000           mov     eax, [eax+$02DC]

* Reference to: controls.TControl.SetColor(TControl;TColor);
|
0049B9C8   E81F65F9FF             call    00431EEC
0049B9CD   BA05000080             mov     edx, $80000005

* Reference to FrmFDBViewer
|
0049B9D2   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.SaveItemGrid : TStringGrid
|
0049B9D5   8B80E0020000           mov     eax, [eax+$02E0]

* Reference to: controls.TControl.SetColor(TControl;TColor);
|
0049B9DB   E80C65F9FF             call    00431EEC
0049B9E0   59                     pop     ecx
0049B9E1   59                     pop     ecx
0049B9E2   5D                     pop     ebp
0049B9E3   C3                     ret

*)
end;

procedure TFrmFDBViewer.BtnApplyClick(Sender : TObject);
begin
(*
0049BA08   55                     push    ebp
0049BA09   8BEC                   mov     ebp, esp
0049BA0B   83C4DC                 add     esp, -$24
0049BA0E   8955DC                 mov     [ebp-$24], edx
0049BA11   8945FC                 mov     [ebp-$04], eax

* Reference to FrmFDBViewer
|
0049BA14   8B45FC                 mov     eax, [ebp-$04]
0049BA17   051C030000             add     eax, +$0000031C
0049BA1C   8945F4                 mov     [ebp-$0C], eax

* Reference to FrmFDBViewer
|
0049BA1F   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.HumanGrid : TStringGrid
|
0049BA22   8B80D4020000           mov     eax, [eax+$02D4]
0049BA28   8945F0                 mov     [ebp-$10], eax

* Reference to FrmFDBViewer
|
0049BA2B   8B45FC                 mov     eax, [ebp-$04]
0049BA2E   05E4040000             add     eax, +$000004E4
0049BA33   8945EC                 mov     [ebp-$14], eax

* Reference to FrmFDBViewer
|
0049BA36   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.BagItemGrid : TStringGrid
|
0049BA39   8B80D8020000           mov     eax, [eax+$02D8]
0049BA3F   8945E8                 mov     [ebp-$18], eax
0049BA42   55                     push    ebp
0049BA43   8B55EC                 mov     edx, [ebp-$14]
0049BA46   B801000000             mov     eax, $00000001

* Reference to: viewrcd.Proc_0049B9E8
|
0049BA4B   E898FFFFFF             call    0049B9E8
0049BA50   59                     pop     ecx
0049BA51   55                     push    ebp
0049BA52   8B45EC                 mov     eax, [ebp-$14]
0049BA55   8D5018                 lea     edx, [eax+$18]
0049BA58   B802000000             mov     eax, $00000002

* Reference to: viewrcd.Proc_0049B9E8
|
0049BA5D   E886FFFFFF             call    0049B9E8
0049BA62   59                     pop     ecx
0049BA63   55                     push    ebp
0049BA64   8B45EC                 mov     eax, [ebp-$14]
0049BA67   8D5048                 lea     edx, [eax+$48]
0049BA6A   B803000000             mov     eax, $00000003

* Reference to: viewrcd.Proc_0049B9E8
|
0049BA6F   E874FFFFFF             call    0049B9E8
0049BA74   59                     pop     ecx
0049BA75   55                     push    ebp
0049BA76   8B45EC                 mov     eax, [ebp-$14]
0049BA79   8D5060                 lea     edx, [eax+$60]
0049BA7C   B804000000             mov     eax, $00000004

* Reference to: viewrcd.Proc_0049B9E8
|
0049BA81   E862FFFFFF             call    0049B9E8
0049BA86   59                     pop     ecx
0049BA87   55                     push    ebp
0049BA88   8B45EC                 mov     eax, [ebp-$14]
0049BA8B   8D5078                 lea     edx, [eax+$78]
0049BA8E   B805000000             mov     eax, $00000005

* Reference to: viewrcd.Proc_0049B9E8
|
0049BA93   E850FFFFFF             call    0049B9E8
0049BA98   59                     pop     ecx
0049BA99   55                     push    ebp
0049BA9A   8B45EC                 mov     eax, [ebp-$14]
0049BA9D   8D9090000000           lea     edx, [eax+$0090]
0049BAA3   B806000000             mov     eax, $00000006

* Reference to: viewrcd.Proc_0049B9E8
|
0049BAA8   E83BFFFFFF             call    0049B9E8
0049BAAD   59                     pop     ecx
0049BAAE   55                     push    ebp
0049BAAF   8B45EC                 mov     eax, [ebp-$14]
0049BAB2   8D90A8000000           lea     edx, [eax+$00A8]
0049BAB8   B807000000             mov     eax, $00000007

* Reference to: viewrcd.Proc_0049B9E8
|
0049BABD   E826FFFFFF             call    0049B9E8
0049BAC2   59                     pop     ecx
0049BAC3   55                     push    ebp
0049BAC4   8B45EC                 mov     eax, [ebp-$14]
0049BAC7   8D90C0000000           lea     edx, [eax+$00C0]
0049BACD   B808000000             mov     eax, $00000008

* Reference to: viewrcd.Proc_0049B9E8
|
0049BAD2   E811FFFFFF             call    0049B9E8
0049BAD7   59                     pop     ecx
0049BAD8   33C0                   xor     eax, eax
0049BADA   8945F8                 mov     [ebp-$08], eax
0049BADD   55                     push    ebp
0049BADE   8B45F8                 mov     eax, [ebp-$08]
0049BAE1   8D0440                 lea     eax, [eax+eax*2]
0049BAE4   8B55EC                 mov     edx, [ebp-$14]
0049BAE7   8D94C2D8000000         lea     edx, [edx+eax*8+$00D8]
0049BAEE   8B45F8                 mov     eax, [ebp-$08]
0049BAF1   83C009                 add     eax, +$09

* Reference to: viewrcd.Proc_0049B9E8
|
0049BAF4   E8EFFEFFFF             call    0049B9E8
0049BAF9   59                     pop     ecx
0049BAFA   FF45F8                 inc     dword ptr [ebp-$08]
0049BAFD   837DF82E               cmp     dword ptr [ebp-$08], +$2E
0049BB01   75DA                   jnz     0049BADD

* Reference to FrmFDBViewer
|
0049BB03   8B45FC                 mov     eax, [ebp-$04]
0049BB06   050C0A0000             add     eax, +$00000A0C
0049BB0B   8945E4                 mov     [ebp-$1C], eax

* Reference to FrmFDBViewer
|
0049BB0E   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmFDBViewer.UseMagicGrid : TStringGrid
|
0049BB11   8B80DC020000           mov     eax, [eax+$02DC]
0049BB17   8945E0                 mov     [ebp-$20], eax
0049BB1A   8BE5                   mov     esp, ebp
0049BB1C   5D                     pop     ebp
0049BB1D   C3                     ret

*)
end;

procedure TFrmFDBViewer.ResetPositionClick(Sender : TObject);
begin
(*
0049BB20   55                     push    ebp
0049BB21   8BEC                   mov     ebp, esp
0049BB23   83C4F8                 add     esp, -$08
0049BB26   8955F8                 mov     [ebp-$08], edx
0049BB29   8945FC                 mov     [ebp-$04], eax

* Reference to FrmFDBViewer
|
0049BB2C   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TFrmFDBViewer.OFFS_0354
|
0049BB2F   66C780540300000000     mov     word ptr [eax+$0354], $0000

* Reference to FrmFDBViewer
|
0049BB38   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TFrmFDBViewer.OFFS_0388
|
0049BB3B   C6808803000000         mov     byte ptr [eax+$0388], $00

* Reference to TFrmFDBExplore instance
|
0049BB42   A18CC14A00             mov     eax, dword ptr [$004AC18C]
0049BB47   8B00                   mov     eax, [eax]

* Reference to : TFrmFDBExplore._PROC_004A5944()
|
0049BB49   E8F69D0000             call    004A5944
0049BB4E   59                     pop     ecx
0049BB4F   59                     pop     ecx
0049BB50   5D                     pop     ebp
0049BB51   C3                     ret

*)
end;

procedure TFrmFDBViewer.ShowHumData();
//0x0049A054
begin
  if HumanGrid.Visible then    ShowHumanInfo();
  if BagItemGrid.Visible then  ShowBagItems();
  if UseMagicGrid.Visible then ShowUseMagic();
  if SaveItemGrid.Visible then ShowSaveItem();
end;

procedure TFrmFDBViewer.sub_49A0C0();
begin
  HumanGrid.Cells[0,1]:='À˜“˝∫≈';
  HumanGrid.Cells[1,1]:='√˚≥∆';
  HumanGrid.Cells[2,1]:='µÿÕº';
  HumanGrid.Cells[3,1]:='CX';
  HumanGrid.Cells[4,1]:='CY';
  HumanGrid.Cells[5,1]:='∑ΩœÚ';
  HumanGrid.Cells[6,1]:='÷∞“µ';
  HumanGrid.Cells[7,1]:='–‘±';
  HumanGrid.Cells[8,1]:='Õ∑∑¢';
  HumanGrid.Cells[9,1]:='Ω±“ ˝';
  HumanGrid.Cells[10,1]:='±√˚';
  HumanGrid.Cells[11,1]:='Home';

  HumanGrid.Cells[0,3]:='HomeX';
  HumanGrid.Cells[1,3]:='HomeY';
  HumanGrid.Cells[2,3]:='µ»º∂';
  HumanGrid.Cells[3,3]:='AC';
  HumanGrid.Cells[4,3]:='MAC';
  HumanGrid.Cells[5,3]:='Reserved1';
  HumanGrid.Cells[6,3]:='DC/1';
  HumanGrid.Cells[7,3]:='DC/2';
  HumanGrid.Cells[8,3]:='MC/1';
  HumanGrid.Cells[9,3]:='MC/2';
  HumanGrid.Cells[10,3]:='SC/1';
  HumanGrid.Cells[11,3]:='SC/2';

  HumanGrid.Cells[0,5]:='Reserved2';
  HumanGrid.Cells[1,5]:='HP';
  HumanGrid.Cells[2,5]:='MaxHP';
  HumanGrid.Cells[3,5]:='MP';
  HumanGrid.Cells[4,5]:='MaxMP';
  HumanGrid.Cells[5,5]:='Reserved2';
  HumanGrid.Cells[6,5]:='µ±«∞æ≠—È';
  HumanGrid.Cells[7,5]:='…˝º∂æ≠—È';
  HumanGrid.Cells[8,5]:='PKµ„ ˝';
  HumanGrid.Cells[9,5]:='';
  HumanGrid.Cells[10,5]:='µ«¬º’ ∫≈';
  HumanGrid.Cells[11,5]:='◊Ó∫Ûµ«¬º ±º‰';

  HumanGrid.Cells[0,7]:='≈‰≈º';
  HumanGrid.Cells[1,7]:=' ¶ÕΩ';
  HumanGrid.Cells[2,7]:='≤÷ø‚√‹¬Î';
  HumanGrid.Cells[3,7]:='…˘Õ˚µ„';
  HumanGrid.Cells[4,7]:='';
  HumanGrid.Cells[5,7]:='';
  HumanGrid.Cells[6,7]:='';
  HumanGrid.Cells[7,7]:='';
  HumanGrid.Cells[8,7]:='';
  HumanGrid.Cells[9,7]:='';
  HumanGrid.Cells[10,7]:='';
  HumanGrid.Cells[11,7]:='';
(*
* Possible String Reference to: 'HP'
* Possible String Reference to: 'MaxHP'
* Possible String Reference to: 'MP'
* Possible String Reference to: 'MaxMP'
* Possible String Reference to: 'Reserved2'
* Possible String Reference to: 'Exp'
* Possible String Reference to: 'MaxExp'
* Possible String Reference to: 'PK-Point'
* Possible String Reference to: 'ID'
* Possible String Reference to: 'Latest'
|
0049A3EE   68C8A94900             push    $0049A9C8
0049A3F3   B905000000             mov     ecx, $00000005
0049A3F8   BA0B000000             mov     edx, $0000000B
0049A3FD   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A400   E86FCEFFFF             call    00497274
0049A405   6A00                   push    $00
0049A407   B907000000             mov     ecx, $00000007
0049A40C   33D2                   xor     edx, edx
0049A40E   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A411   E85ECEFFFF             call    00497274
0049A416   6A00                   push    $00
0049A418   B907000000             mov     ecx, $00000007
0049A41D   BA01000000             mov     edx, $00000001
0049A422   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A425   E84ACEFFFF             call    00497274
0049A42A   6A00                   push    $00
0049A42C   B907000000             mov     ecx, $00000007
0049A431   BA02000000             mov     edx, $00000002
0049A436   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A439   E836CEFFFF             call    00497274
0049A43E   6A00                   push    $00
0049A440   B907000000             mov     ecx, $00000007
0049A445   BA03000000             mov     edx, $00000003
0049A44A   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A44D   E822CEFFFF             call    00497274
0049A452   6A00                   push    $00
0049A454   B907000000             mov     ecx, $00000007
0049A459   BA04000000             mov     edx, $00000004
0049A45E   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A461   E80ECEFFFF             call    00497274
0049A466   6A00                   push    $00
0049A468   B907000000             mov     ecx, $00000007
0049A46D   BA05000000             mov     edx, $00000005
0049A472   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A475   E8FACDFFFF             call    00497274
0049A47A   6A00                   push    $00
0049A47C   B907000000             mov     ecx, $00000007
0049A481   BA06000000             mov     edx, $00000006
0049A486   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A489   E8E6CDFFFF             call    00497274
0049A48E   6A00                   push    $00
0049A490   B907000000             mov     ecx, $00000007
0049A495   BA07000000             mov     edx, $00000007
0049A49A   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A49D   E8D2CDFFFF             call    00497274
0049A4A2   6A00                   push    $00
0049A4A4   B907000000             mov     ecx, $00000007
0049A4A9   BA08000000             mov     edx, $00000008
0049A4AE   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A4B1   E8BECDFFFF             call    00497274
0049A4B6   6A00                   push    $00
0049A4B8   B907000000             mov     ecx, $00000007
0049A4BD   BA09000000             mov     edx, $00000009
0049A4C2   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A4C5   E8AACDFFFF             call    00497274
0049A4CA   6A00                   push    $00
0049A4CC   B907000000             mov     ecx, $00000007
0049A4D1   BA0A000000             mov     edx, $0000000A
0049A4D6   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A4D9   E896CDFFFF             call    00497274
0049A4DE   6A00                   push    $00
0049A4E0   B907000000             mov     ecx, $00000007
0049A4E5   BA0B000000             mov     edx, $0000000B
0049A4EA   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A4ED   E882CDFFFF             call    00497274
0049A4F2   6A00                   push    $00
0049A4F4   B909000000             mov     ecx, $00000009
0049A4F9   33D2                   xor     edx, edx
0049A4FB   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A4FE   E871CDFFFF             call    00497274
0049A503   6A00                   push    $00
0049A505   B909000000             mov     ecx, $00000009
0049A50A   BA01000000             mov     edx, $00000001
0049A50F   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A512   E85DCDFFFF             call    00497274
0049A517   6A00                   push    $00
0049A519   B909000000             mov     ecx, $00000009
0049A51E   BA02000000             mov     edx, $00000002
0049A523   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A526   E849CDFFFF             call    00497274
0049A52B   6A00                   push    $00
0049A52D   B909000000             mov     ecx, $00000009
0049A532   BA03000000             mov     edx, $00000003
0049A537   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A53A   E835CDFFFF             call    00497274
0049A53F   6A00                   push    $00
0049A541   B909000000             mov     ecx, $00000009
0049A546   BA04000000             mov     edx, $00000004
0049A54B   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A54E   E821CDFFFF             call    00497274
0049A553   6A00                   push    $00
0049A555   B909000000             mov     ecx, $00000009
0049A55A   BA05000000             mov     edx, $00000005
0049A55F   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A562   E80DCDFFFF             call    00497274
0049A567   6A00                   push    $00
0049A569   B909000000             mov     ecx, $00000009
0049A56E   BA06000000             mov     edx, $00000006
0049A573   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A576   E8F9CCFFFF             call    00497274
0049A57B   6A00                   push    $00
0049A57D   B909000000             mov     ecx, $00000009
0049A582   BA07000000             mov     edx, $00000007
0049A587   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A58A   E8E5CCFFFF             call    00497274
0049A58F   6A00                   push    $00
0049A591   B909000000             mov     ecx, $00000009
0049A596   BA08000000             mov     edx, $00000008
0049A59B   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A59E   E8D1CCFFFF             call    00497274
0049A5A3   6A00                   push    $00
0049A5A5   B909000000             mov     ecx, $00000009
0049A5AA   BA09000000             mov     edx, $00000009
0049A5AF   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A5B2   E8BDCCFFFF             call    00497274
0049A5B7   6A00                   push    $00
0049A5B9   B909000000             mov     ecx, $00000009
0049A5BE   BA0A000000             mov     edx, $0000000A
0049A5C3   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A5C6   E8A9CCFFFF             call    00497274
0049A5CB   6A00                   push    $00
0049A5CD   B909000000             mov     ecx, $00000009
0049A5D2   BA0B000000             mov     edx, $0000000B
0049A5D7   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A5DA   E895CCFFFF             call    00497274
0049A5DF   6A00                   push    $00
0049A5E1   B90B000000             mov     ecx, $0000000B
0049A5E6   33D2                   xor     edx, edx
0049A5E8   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A5EB   E884CCFFFF             call    00497274
0049A5F0   6A00                   push    $00
0049A5F2   B90B000000             mov     ecx, $0000000B
0049A5F7   BA01000000             mov     edx, $00000001
0049A5FC   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A5FF   E870CCFFFF             call    00497274
0049A604   6A00                   push    $00
0049A606   B90B000000             mov     ecx, $0000000B
0049A60B   BA02000000             mov     edx, $00000002
0049A610   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A613   E85CCCFFFF             call    00497274
0049A618   6A00                   push    $00
0049A61A   B90B000000             mov     ecx, $0000000B
0049A61F   BA03000000             mov     edx, $00000003
0049A624   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A627   E848CCFFFF             call    00497274
0049A62C   6A00                   push    $00
0049A62E   B90B000000             mov     ecx, $0000000B
0049A633   BA04000000             mov     edx, $00000004
0049A638   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A63B   E834CCFFFF             call    00497274
0049A640   6A00                   push    $00
0049A642   B90B000000             mov     ecx, $0000000B
0049A647   BA05000000             mov     edx, $00000005
0049A64C   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A64F   E820CCFFFF             call    00497274
0049A654   6A00                   push    $00
0049A656   B90B000000             mov     ecx, $0000000B
0049A65B   BA06000000             mov     edx, $00000006
0049A660   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A663   E80CCCFFFF             call    00497274
0049A668   6A00                   push    $00
0049A66A   B90B000000             mov     ecx, $0000000B
0049A66F   BA07000000             mov     edx, $00000007
0049A674   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A677   E8F8CBFFFF             call    00497274
0049A67C   6A00                   push    $00
0049A67E   B90B000000             mov     ecx, $0000000B
0049A683   BA08000000             mov     edx, $00000008
0049A688   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A68B   E8E4CBFFFF             call    00497274
0049A690   6A00                   push    $00
0049A692   B90B000000             mov     ecx, $0000000B
0049A697   BA09000000             mov     edx, $00000009
0049A69C   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A69F   E8D0CBFFFF             call    00497274
0049A6A4   6A00                   push    $00
0049A6A6   B90B000000             mov     ecx, $0000000B
0049A6AB   BA0A000000             mov     edx, $0000000A
0049A6B0   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A6B3   E8BCCBFFFF             call    00497274
0049A6B8   6A00                   push    $00
0049A6BA   B90B000000             mov     ecx, $0000000B
0049A6BF   BA0B000000             mov     edx, $0000000B
0049A6C4   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A6C7   E8A8CBFFFF             call    00497274
0049A6CC   6A00                   push    $00
0049A6CE   B90D000000             mov     ecx, $0000000D
0049A6D3   33D2                   xor     edx, edx
0049A6D5   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A6D8   E897CBFFFF             call    00497274
0049A6DD   6A00                   push    $00
0049A6DF   B90D000000             mov     ecx, $0000000D
0049A6E4   BA01000000             mov     edx, $00000001
0049A6E9   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A6EC   E883CBFFFF             call    00497274
0049A6F1   6A00                   push    $00
0049A6F3   B90D000000             mov     ecx, $0000000D
0049A6F8   BA02000000             mov     edx, $00000002
0049A6FD   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A700   E86FCBFFFF             call    00497274
0049A705   6A00                   push    $00
0049A707   B90D000000             mov     ecx, $0000000D
0049A70C   BA03000000             mov     edx, $00000003
0049A711   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A714   E85BCBFFFF             call    00497274
0049A719   6A00                   push    $00
0049A71B   B90D000000             mov     ecx, $0000000D
0049A720   BA04000000             mov     edx, $00000004
0049A725   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A728   E847CBFFFF             call    00497274
0049A72D   68D8A94900             push    $0049A9D8
0049A732   B90D000000             mov     ecx, $0000000D
0049A737   BA05000000             mov     edx, $00000005
0049A73C   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A73F   E830CBFFFF             call    00497274
0049A744   68D8A94900             push    $0049A9D8
0049A749   B90D000000             mov     ecx, $0000000D
0049A74E   BA06000000             mov     edx, $00000006
0049A753   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A756   E819CBFFFF             call    00497274
0049A75B   68D8A94900             push    $0049A9D8
0049A760   B90D000000             mov     ecx, $0000000D
0049A765   BA07000000             mov     edx, $00000007
0049A76A   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A76D   E802CBFFFF             call    00497274
0049A772   68D8A94900             push    $0049A9D8
0049A777   B90D000000             mov     ecx, $0000000D
0049A77C   BA08000000             mov     edx, $00000008
0049A781   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A784   E8EBCAFFFF             call    00497274
0049A789   68D8A94900             push    $0049A9D8
0049A78E   B90D000000             mov     ecx, $0000000D
0049A793   BA09000000             mov     edx, $00000009
0049A798   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A79B   E8D4CAFFFF             call    00497274
0049A7A0   68D8A94900             push    $0049A9D8
0049A7A5   B90D000000             mov     ecx, $0000000D
0049A7AA   BA0A000000             mov     edx, $0000000A
0049A7AF   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A7B2   E8BDCAFFFF             call    00497274
0049A7B7   68D8A94900             push    $0049A9D8
0049A7BC   B90D000000             mov     ecx, $0000000D
0049A7C1   BA0B000000             mov     edx, $0000000B
0049A7C6   8B45F8                 mov     eax, [ebp-$08]

* Reference to: grids.TStringGrid.SetCells(TStringGrid;Integer;Integer;AnsiString);
|
0049A7C9   E8A6CAFFFF             call    00497274
0049A7CE   59                     pop     ecx
0049A7CF   59                     pop     ecx
0049A7D0   5D                     pop     ebp
0049A7D1   C3                     ret

*)
end;

procedure TFrmFDBViewer.sub_49A9DC();
begin
  BagItemGrid.Cells[0,0]:='ŒÔ∆∑∫≈';
  BagItemGrid.Cells[1,0]:='ŒÔ∆∑ID';
  BagItemGrid.Cells[2,0]:='ŒÔ∆∑∫≈';
  BagItemGrid.Cells[3,0]:='≥÷æ√';
end;

procedure TFrmFDBViewer.sub_49AA84();
begin
  SaveItemGrid.Cells[0,0]:='ŒÔ∆∑œµ¡–∫≈';
  SaveItemGrid.Cells[1,0]:='ŒÔ∆∑∫≈';
  SaveItemGrid.Cells[2,0]:='≥÷æ√';
end;

procedure TFrmFDBViewer.sub_49AB10();
begin
  UseMagicGrid.Cells[0,0]:='ººƒ‹√˚≥∆';
  UseMagicGrid.Cells[1,0]:='øÏΩ›º¸';
  UseMagicGrid.Cells[2,0]:='–ﬁ¡∑◊¥Ã¨';
end;

procedure TFrmFDBViewer.ShowBagItem(nIndex:Integer;sName:String;Item:TUserItem);
begin
  if Item.wIndex > 0 then begin
    BagItemGrid.Cells[0,nIndex]:=sName;
    BagItemGrid.Cells[1,nIndex]:=IntToStr(Item.MakeIndex);
    BagItemGrid.Cells[2,nIndex]:=IntToStr(Item.wIndex);
    BagItemGrid.Cells[3,nIndex]:=IntToStr(Item.Dura) + '/' + IntToStr(Item.DuraMax);
  end else begin
    BagItemGrid.Cells[0,nIndex]:=sName;
    BagItemGrid.Cells[1,nIndex]:='';
    BagItemGrid.Cells[2,nIndex]:='';
    BagItemGrid.Cells[3,nIndex]:='';
  end;


end;
procedure TFrmFDBViewer.ShowHumanInfo();
//0x049AB9C
var
  HumData:pTHumData;
begin
  HumData:=@ChrRecord.Data;
  HumanGrid.Cells[0,2]:=IntToStr(n2F8);
  HumanGrid.Cells[1,2]:=HumData.sChrName;
  HumanGrid.Cells[2,2]:=HumData.sCurMap;
  HumanGrid.Cells[3,2]:=IntToStr(HumData.wCurX);
  HumanGrid.Cells[4,2]:=IntToStr(HumData.wCurY);
  HumanGrid.Cells[5,2]:=IntToStr(HumData.btDir);
  HumanGrid.Cells[6,2]:=IntToStr(HumData.btJob);
  HumanGrid.Cells[7,2]:=IntToStr(HumData.btSex);
  HumanGrid.Cells[8,2]:=IntToStr(HumData.btHair);
  HumanGrid.Cells[9,2]:=IntToStr(HumData.nGold);
  HumanGrid.Cells[10,2]:=HumData.sDearName;
  HumanGrid.Cells[11,2]:=HumData.sHomeMap;

  HumanGrid.Cells[0,4]:=IntToStr(HumData.wHomeX);
  HumanGrid.Cells[1,4]:=IntToStr(HumData.wHomeY);
  HumanGrid.Cells[2,4]:=IntToStr(HumData.Abil.Level);
  HumanGrid.Cells[3,4]:=IntToStr(HumData.Abil.AC);
  HumanGrid.Cells[4,4]:=IntToStr(HumData.Abil.MAC);
//  HumanGrid.Cells[5,4]:=IntToStr(HumData.Abil.bt49);
  HumanGrid.Cells[6,4]:=IntToStr(LoByte(HumData.Abil.DC));
  HumanGrid.Cells[7,4]:=IntToStr(HiByte(HumData.Abil.DC));
  HumanGrid.Cells[8,4]:=IntToStr(LoByte(HumData.Abil.MC));
  HumanGrid.Cells[9,4]:=IntToStr(HiByte(HumData.Abil.MC));
  HumanGrid.Cells[10,4]:=IntToStr(LoByte(HumData.Abil.SC));
  HumanGrid.Cells[11,4]:=IntToStr(HiByte(HumData.Abil.SC));

//  HumanGrid.Cells[0,6]:=IntToStr(HumData.Abil.bt48);
  HumanGrid.Cells[1,6]:=IntToStr(HumData.Abil.HP);
  HumanGrid.Cells[2,6]:=IntToStr(HumData.Abil.HP);
  HumanGrid.Cells[3,6]:=IntToStr(HumData.Abil.MaxMP);
  HumanGrid.Cells[4,6]:=IntToStr(HumData.Abil.MaxMP);
//  HumanGrid.Cells[5,6]:=IntToStr(HumData.Abil.bt48);
  HumanGrid.Cells[6,6]:=IntToStr(HumData.Abil.Exp);
  HumanGrid.Cells[7,6]:=IntToStr(HumData.Abil.MaxExp);
  HumanGrid.Cells[8,6]:=IntToStr(HumData.nPKPoint);
  HumanGrid.Cells[9,6]:='';
  HumanGrid.Cells[10,6]:=HumData.sAccount;
  HumanGrid.Cells[11,6]:=DateTimeToStr(ChrRecord.Header.dCreateDate);

  HumanGrid.Cells[0,8]:=HumData.sDearName;
  HumanGrid.Cells[1,8]:=HumData.sMasterName;
  HumanGrid.Cells[2,8]:=HumData.sStoragePwd;
  HumanGrid.Cells[3,8]:=IntToStr(HumData.btCreditPoint);

  
end;
//0049B295
procedure TFrmFDBViewer.ShowBagItems();
var
  i,ii:Integer;
begin
  for i:= 1 to BagItemGrid.RowCount - 1 do begin
    for ii:= 0 to BagItemGrid.ColCount - 1 do begin
      BagItemGrid.Cells[ii,i]:='';
    end;
  end;
  ShowBagItem(1,'“¬∑˛',ChrRecord.Data.HumItems[0]);
  ShowBagItem(2,'Œ‰∆˜',ChrRecord.Data.HumItems[1]);
  ShowBagItem(3,'’’√˜ŒÔ',ChrRecord.Data.HumItems[2]);
  ShowBagItem(4,'Õ∑ø¯',ChrRecord.Data.HumItems[3]);
  ShowBagItem(5,'œÓ¡¥',ChrRecord.Data.HumItems[4]);
  ShowBagItem(6,' ÷ÔÌ◊Û',ChrRecord.Data.HumItems[5]);
  ShowBagItem(7,' ÷ÔÌ”“',ChrRecord.Data.HumItems[6]);
  ShowBagItem(8,'Ω‰÷∏◊Û',ChrRecord.Data.HumItems[7]);
  ShowBagItem(9,'Ω‰÷∏”“',ChrRecord.Data.HumItems[8]);
  for i:= Low(ChrRecord.Data.BagItems) to High(ChrRecord.Data.BagItems) do begin
    ShowBagItem(i + 9,IntToStr(i + 1),ChrRecord.Data.BagItems[i]);
  end;
end;

procedure TFrmFDBViewer.ShowUseMagic();
//0x0049B4D8
var
  i,ii:Integer;
begin
  for i:= 1 to UseMagicGrid.RowCount - 1 do begin
    for ii:= 0 to UseMagicGrid.ColCount - 1 do begin
      UseMagicGrid.Cells[ii,i]:='';
    end;
  end;
 { for I := Low(ChrRecord.Data.Magic) to High(ChrRecord.Data.Magic) do begin
   // if ChrRecord.Data.Magic[i].wMagIdx <= 0 then break;
    UseMagicGrid.Cells[0,i+ 1]:=IntToStr(ChrRecord.Data.Magic[i].wMagIdx);
//    UseMagicGrid.Cells[1,i+ 1]:=IntToStr(ChrRecord.Data.Magic[i].bt06);
    UseMagicGrid.Cells[1,i+ 1]:=Chr(ChrRecord.Data.Magic[i].btKey);
    UseMagicGrid.Cells[2,i+ 1]:=IntToStr(ChrRecord.Data.Magic[i].nTranPoint);
  //end;   }
end;

procedure TFrmFDBViewer.ShowSaveItem();
//0x0049B628
var
  i,ii:Integer;
begin
  for i:= 1 to SaveItemGrid.RowCount - 1 do begin
    for ii:= 0 to SaveItemGrid.ColCount - 1 do begin
      SaveItemGrid.Cells[ii,i]:='';
    end;
  end;
  for I := Low(ChrRecord.Data.StorageItems) to High(ChrRecord.Data.StorageItems) do begin
    if ChrRecord.Data.StorageItems[i].wIndex <= 0 then Continue;
    SaveItemGrid.Cells[0,i+ 1]:=IntToStr(ChrRecord.Data.StorageItems[i].MakeIndex);
    SaveItemGrid.Cells[1,i+ 1]:=IntToStr(ChrRecord.Data.StorageItems[i].wIndex);
    SaveItemGrid.Cells[2,i+ 1]:=IntToStr(ChrRecord.Data.StorageItems[i].Dura) + '/' +
                                IntToStr(ChrRecord.Data.StorageItems[i].DuraMax);
  end;
end;

procedure TFrmFDBViewer._PROC_0049B9E4(Sender : TObject);
begin
(*
0049B9E4   000400                 add     [eax+eax], al
0049B9E7   00558B                 add     [ebp-$75], dl
0049B9EA   EC                     in      al, dx
0049B9EB   83C4F4                 add     esp, -$0C
0049B9EE   8955F4                 mov     [ebp-$0C], edx
0049B9F1   8945F8                 mov     [ebp-$08], eax
0049B9F4   8B4508                 mov     eax, [ebp+$08]
0049B9F7   8B40FC                 mov     eax, [eax-$04]

* Reference to control TFrmFDBViewer.BagItemGrid : TStringGrid
|
0049B9FA   8B80D8020000           mov     eax, [eax+$02D8]
0049BA00   8945FC                 mov     [ebp-$04], eax
0049BA03   8BE5                   mov     esp, ebp
0049BA05   5D                     pop     ebp
0049BA06   C3                     ret

*)
end;

procedure TFrmFDBViewer._PROC_0049BB54(Sender : TObject);
begin
(*
0049BB54   55                     push    ebp
0049BB55   8BEC                   mov     ebp, esp
0049BB57   33C0                   xor     eax, eax
0049BB59   55                     push    ebp

* Possible String Reference to: 'ÈñzˆˇÎ¯]√ã¿É-\€J'
|
0049BB5A   6879BB4900             push    $0049BB79

***** TRY
|
0049BB5F   64FF30                 push    dword ptr fs:[eax]
0049BB62   648920                 mov     fs:[eax], esp
0049BB65   FF055CDB4A00           inc     dword ptr [$004ADB5C]
0049BB6B   33C0                   xor     eax, eax
0049BB6D   5A                     pop     edx
0049BB6E   59                     pop     ecx
0049BB6F   59                     pop     ecx
0049BB70   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√ã¿É-\€J'
|
0049BB73   6880BB4900             push    $0049BB80
0049BB78   C3                     ret


* Reference to: system.@HandleFinally;
|
0049BB79   E9967AF6FF             jmp     00403614
0049BB7E   EBF8                   jmp     0049BB78

****** END
|
0049BB80   5D                     pop     ebp
0049BB81   C3                     ret

*)
end;

procedure TFrmFDBViewer._PROC_0049BB84(Sender : TObject);
begin
(*
0049BB84   832D5CDB4A0001         sub     dword ptr [$004ADB5C], +$01
0049BB8B   C3                     ret

*)
end;

end.